### ISSUE TITLE
different result count

### ISSUE THREAD

**Issue by radius314** [jbraswell/tomato#18] opened 2018-03-15 04:26 UTC
Sandwich and Tomato are returning different result counts for this query.  Haven't quite nailed down what's going.

Sandwich query results in 1071 meetings:

https://na-bmlt.org/_/sandwich/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=NC&sort_keys=meeting_name

Tomato query results in 912 meetings:

https://tomato.na-bmlt.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=NC&sort_keys=meeting_name

**Comment by jbraswell** [comment] 2018-03-15 04:30
Well, there are definitely only 912 meetings in the tomato db with location_province == 'NC'

```
tomato=# select count(*) from api_meeting inner join api_meetinginfo on api_meeting.id = api_meetinginfo.meeting_id where location_province='NC';
 count 
-------
   913
```

**Comment by radius314** [comment] 2018-03-15 04:31
going to do some additional inspection.

**Comment by radius314** [comment] 2018-03-15 04:40
NC is tabulated by hitting 3 root servers:

Carolina Region (724 meetings)
http://crna.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=NC&sort_keys=meeting_name

North Carolina (337 meetings)
https://bmlt.ncregion-na.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=NC&sort_keys=meeting_name

Autonomy Zone (10 meetings)
https://metrorichna.org/BMLT/main_server/client_interface/json/?switcher=GetSearchResults&meeting_key=location_province&meeting_key_value=NC&sort_keys=meeting_name

**Comment by jbraswell** [comment] 2018-03-15 04:46
I know what the issue is.

```
tomato=# select count(*) from api_meeting inner join api_meetinginfo on api_meeting.id = api_meetinginfo.meeting_id where location_province='NC' and root_server_id=6;
 count 
-------
   565
(1 row)
```

That's the crna.org server. A bunch of meetings on that server are invalid, and are not getting imported. Or, they're invalid from tomato's standpoint. There are two issues with meetings on that server.

1. They have a weekday_tinyint of 8.
2. They reference in invalid service body (or at least the service body they reference is not returned by GetServiceBodies)

**Comment by radius314** [comment] 2018-03-15 04:47
Any way to export that list so I can share it with the admin?

**Comment by jbraswell** [comment] 2018-03-15 04:48
Yeah. I am saving objects that fail to import to the database. Let me get them for you.

**Comment by radius314** [comment] 2018-03-15 04:50
👍

**Comment by jbraswell** [comment] 2018-03-15 04:56
I just threw some special logging together and ran an import of their server on my development VM

```
/home/jbraswell/.virtualenvs/na/bin/python /home/jbraswell/tomato/src/manage.py import_root_servers
starting daemon
retrieving root servers
importing root server http://crna.org/main_server/
importing service bodies
importing formats
importing meetings
Error parsing meeting: Invalid service_body, id_bigint '1', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '2', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '3', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '4', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '5', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '6', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '7', service_body_bigint '1', weekday_tinyint '1'
Error parsing meeting: Invalid service_body, id_bigint '8', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '516', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '9', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '10', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '818', service_body_bigint '21', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '11', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '12', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '13', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '517', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '819', service_body_bigint '21', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '14', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '518', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '519', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '15', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '16', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '17', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '520', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '521', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '18', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '19', service_body_bigint '1', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '522', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '820', service_body_bigint '21', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '821', service_body_bigint '21', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '523', service_body_bigint '13', weekday_tinyint '2'
Error parsing meeting: Invalid service_body, id_bigint '20', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '524', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '24', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '525', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '22', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '23', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '526', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '25', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '527', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '822', service_body_bigint '21', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '26', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '27', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '528', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '28', service_body_bigint '1', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '529', service_body_bigint '13', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '823', service_body_bigint '21', weekday_tinyint '3'
Error parsing meeting: Invalid service_body, id_bigint '29', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '30', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '530', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '21', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '31', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '32', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '33', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '531', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '34', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '35', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '532', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '533', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '824', service_body_bigint '21', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '36', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '534', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '535', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '536', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '537', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '37', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '38', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '39', service_body_bigint '1', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '538', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '539', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '540', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '541', service_body_bigint '13', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '825', service_body_bigint '21', weekday_tinyint '4'
Error parsing meeting: Invalid service_body, id_bigint '40', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '542', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '41', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '42', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '543', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '43', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '544', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '826', service_body_bigint '21', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '44', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '45', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '46', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '545', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '546', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '47', service_body_bigint '1', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '547', service_body_bigint '13', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '827', service_body_bigint '21', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '828', service_body_bigint '21', weekday_tinyint '5'
Error parsing meeting: Invalid service_body, id_bigint '48', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '548', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '49', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '50', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '549', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '550', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '551', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '829', service_body_bigint '21', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '51', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '52', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '552', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '553', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '554', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '53', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '555', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '556', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '54', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '55', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '557', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '558', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '559', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '560', service_body_bigint '13', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '830', service_body_bigint '21', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '56', service_body_bigint '1', weekday_tinyint '6'
Error parsing meeting: Invalid service_body, id_bigint '57', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '561', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '58', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '562', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '59', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '563', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '564', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '60', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '565', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '566', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '61', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '567', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '568', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '569', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '570', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '571', service_body_bigint '13', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '63', service_body_bigint '1', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '831', service_body_bigint '21', weekday_tinyint '7'
Error parsing meeting: Invalid service_body, id_bigint '832', service_body_bigint '21', weekday_tinyint '7'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '126', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '572', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '127', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '128', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '515', service_body_bigint '12', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '573', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '574', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '714', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '715', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '129', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '575', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '716', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '576', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '833', service_body_bigint '21', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '130', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '577', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '131', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '717', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '133', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '578', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '134', service_body_bigint '3', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '579', service_body_bigint '13', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '718', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '719', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '720', service_body_bigint '17', weekday_tinyint '8'
Error parsing meeting: Invalid service_body, id_bigint '834', service_body_bigint '21', weekday_tinyint '8'
Error parsing meeting: Invalid weekday_tinyint, id_bigint '135', service_body_bigint '3', weekday_tinyint '8'
sleeping
```

**Comment by pjaudiomv** [comment] 2018-03-16 02:09
im vice chair of crna.org, and have been trying to clean up the database i was just elected a couple months ago and going one area at a time. i wonder how some weekdays had a tiny init of 8. any tips would be appreciated, patrick joyce webteam.vchair@crna.org,  pjaudiomv@gmail.com. it is definitly a mess and data has been been filled in improperly. just fixed a long/lat that was 0,0

**Comment by pjaudiomv** [comment] 2018-03-16 02:43
on the crna.org bmlt server those meetings have a weekday_tinyint of '7', just checked the mysql databse

**Comment by jbraswell** [comment] 2018-03-16 02:56
When tomato imports from a root server, it does the following.
1. Import Service Bodies returned from http://crna.org/main_server/client_interface/xml/?switcher=GetServiceBodies
2. Import Formats returned from http://crna.org/main_server/client_interface/xml/?switcher=GetFormats
3. Import Meetings returned from http://crna.org/main_server/client_interface/xml/?switcher=GetSearchResults

There are two issues here.
1. Most of your meetings are failing to import because they reference a service body that isn't returned by the GetServiceBodies URL in Step 1. These service bodies have IDs of 1, 13, and 21.
2. There are a handful of meetings coming back from the GetSearchResults URL in step 3 with a weekday_tinyint of 8.

My questions...
1. For the service bodies issue, are there any service bodies in the database with ID 1, 13, or 21? If so, is there anything special about them that might make them not show up in the GetServiceBodies request? If not, are these meetings simply pointing to invalid service bodies, and can they be fixed by editing them to point to the correct service body?
2. For the weekday one... that's really interesting that their weekday_tinyint field is set to '7' in the database. You're absolutely sure about this? If that's the case, then something in the BMLT application code must be changing them to 8 before serving up the response.

I'm going to ping Chris to see if he has any ideas.

**Comment by radius314** [comment] 2018-03-16 03:12
On a slack right now with @pjaudiomv, we are starting to tackle these data items

**Comment by pjaudiomv** [comment] 2018-03-16 03:24
1,13, and 21 are not active service bodies

**Comment by radius314** [comment] 2018-03-16 03:28
Down to 1007, closer to 912

**Comment by jbraswell** [comment] 2018-03-16 03:34
1. Should those inactive service bodies be made active?
2. If not, should those meetings belong to different service bodies?

**Comment by radius314** [comment] 2018-03-16 03:35
The service bodies were deleted, which does not deactivate the meeting.  I had @pjaudiomv make a new fake service body, and then run an update to reattach.  Then manually delete the meetings.

**Comment by jbraswell** [comment] 2018-03-16 03:43
Cool. Are those meetings still around? If so, will someone be putting them back in under real service bodies?

**Comment by radius314** [comment] 2018-03-16 04:33
they are duplicates, or in a different root server because the ASC changed RSCs

**Closed** 2018-03-16 05:11 UTC

**Comment by LittleGreenViper** [comment] 2018-03-16 08:06
Hmm... I’d have to look at the code, and see how I deal with deleted Service bodies. There’s a chance that the meetings are “orphaned.” There should be a way to gather them and bulk reassign them.
The weekday 8 thing looks like a “for loop went too far” bug. I’d have to be able to reproduce it in my localhost to fix it, but I could probably do it.
If there’s a single DB that exhibits the bugs, I’d like a phpMyAdmin dump of it.
